<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * @property load $load
 * @property Bidang_model $Bidang_model
 * @property access $access
 * @property template $template
 * @property session $session
 * @property form_validation $form_validation
 * @property input $input
 */

class Bidang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bidang_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        if (
            $this->session->userdata('logged_in') != "" &&
            ($this->session->userdata('level') == "admin" or $this->session->userdata('level') == "operator")
        ) {
            $bidang         = $this->Bidang_model->get_all();

            $data = array(
                'level_sess'        => $this->access->get_level(),
                'bidang_data'       => $bidang
            );

            $this->template->load('template', 'bidang/list', $data);
        } else {
            header('location:' . base_url() . '');
        }
    }

    public function create()
    {
        if (
            $this->session->userdata('logged_in') != "" &&
            ($this->session->userdata('level') == "admin" or $this->session->userdata('level') == "operator")
        ) {
            $data = array(
                'disable'           => '',
                'button'            => 'Create',
                'action'            => site_url('bidang/create_action'),
                'IdBidang'          => set_value('IdBidang'),
                'Bidang'            => set_value('Bidang'),
            );

            $this->template->load('template', 'bidang/form', $data);
        } else {
            header('location:' . base_url() . '');
        }
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'Bidang'        => $this->input->post('Bidang', TRUE),
            );

            $this->Bidang_model->insert($data);

            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bidang'));
        }
    }

    public function update($id)
    {
        if (
            $this->session->userdata('logged_in') != "" &&
            ($this->session->userdata('level') == "admin" or $this->session->userdata('level') == "operator")
        ) {
            $row        = $this->Bidang_model->get_by_id($id);

            if ($row) {
                $data = array(
                    'disable'       => '',
                    'button'        => 'Update',
                    'action'        => site_url('bidang/update_action'),
                    'IdBidang'      => set_value('IdBidang', $row->IdBidang),
                    'Bidang'        => set_value('Bidang', $row->Bidang),
                );

                $this->template->load('template', 'bidang/form', $data);
            } else {
                $this->session->set_flashdata('message', 'Record Not Found');
                redirect(site_url('bidang'));
            }
        } else {
            header('location:' . base_url() . '');
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('IdBidang', TRUE));
        } else {
            $data = array(
                'Bidang'        => $this->input->post('Bidang', TRUE),
            );

            $this->Bidang_model->update($this->input->post('IdBidang', TRUE), $data);

            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bidang'));
        }
    }

    public function delete($id)
    {
        $row        = $this->Bidang_model->get_by_id($id);

        if ($row) {
            $this->Bidang_model->delete($id);

            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bidang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bidang'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('Bidang', 'Nama Bidang', 'trim|required');
        $this->form_validation->set_rules('IdBidang', 'IdBidang', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Bidang.php */
/* Location: ./application/controllers/Bidang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-22 04:24:22 */
/* http://harviacode.com */