<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * @property load $load
 * @property Content_model $Content_model
 * @property Rating_model $Rating_model
 * @property Unitkerja_model $Unitkerja_model
 * @property template $template
 * @property session $session
 * @property Akun_model $Akun_model
 * @property form_validation $form_validation
 * @property input $input
 * @property db $db
 */

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Content_model');
        $this->load->model('Rating_model');
        $this->load->model('Unitkerja_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $content        = $this->Content_model->get_all_query2();
        $rating         = $this->Rating_model->get_all();

        $param = array(
            'jenis'     => 'Rumah Sehat Jakarta',
            'limit'     => 8,
            'start'     => rand(0, 20)
        );

        $website_ppid   = $this->Unitkerja_model->get_limit($param);

        $data = array(
            'content_data'  => $content,
            'rating_data'   => $rating,
            'website_ppid'  => $website_ppid
        );

        $this->template->load('template2', 'home/index', $data);
    }

    public function pejabat()
    {
        $this->template->load('template2', 'home/pejabat');
    }

    public function berita()
    {
        $this->template->load('template2', 'home/berita');
    }

    public function infokesehatan()
    {
        $this->template->load('template2', 'home/infokesehatan');
    }

    public function konten()
    {
        $this->template->load('template2', 'home/konten');
    }

    public function infografis()
    {
        $this->template->load('template2', 'home/infografis');
    }

    public function video()
    {
        $this->template->load('template2', 'home/video');
    }

    public function kanal()
    {
        $this->template->load('template2', 'home/kanal');
    }

    public function waktu()
    {
        $this->template->load('template2', 'home/waktu');
    }

    public function sosialisasi()
    {
        $this->template->load('template2', 'home/sosialisasi');
    }

    public function maklumat()
    {
        $this->template->load('template2', 'home/maklumat');
    }

    public function upt()
    {
        $website_ppid   = $this->Unitkerja_model->get_jenis('Rumah Sehat Jakarta');

        $data = array(
            'title'             => 'Website PPID UPT/UKPD',
            'website_ppid'      => $website_ppid
        );

        $this->template->load('template2', 'home/ppid_upt_ukpd', $data);
    }

    public function submit_rating()
    {
        date_default_timezone_set('Asia/Bangkok');

        $rating             = $_GET["rating"];
        $komentar           = $_GET["komentar"];
        $data["rating"]     = $_GET["rating"];
        $data["komentar"]   = $_GET["komentar"];

        $q      = $this->db->query("INSERT INTO rating (Rating, Komentar, IP, CreatedDate) values ('" . $rating . "','" . $komentar . "','" . $_SERVER['HTTP_CLIENT_IP'] . "','" . date("Y-m-d H:i:s") . "')");
    }
}

/* End of file Akun.php */
/* Location: ./application/controllers/Akun.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-22 04:24:22 */
/* http://harviacode.com */
