<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/**
 * @property load $load
 * @property Rating_model $Rating_model
 * @property template $template
 */

class Rating extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rating_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $rating         = $this->Rating_model->get_all_data();

        $data = array(
            'rating_all_data'       => $rating
        );

        $this->template->load('template2', 'rating/index', $data);
    }
}

/* End of file Lab.php */
/* Location: ./application/controllers/Lab.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-22 04:24:22 */
/* http://harviacode.com */