<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Seksi_model extends CI_Model
{

    public $table = 'seksi';
    public $id = 'IdSeksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('IdSeksi', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get all query
    function get_all_query()
    {
        $sql = "select a.*, b.Bidang as bidang
                from seksi a 
                left join bidang b on a.IdBidang=b.IdBidang";
        
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('IdSeksi', $q);
    	$this->db->or_like('IdBidang', $q);
    	$this->db->or_like('Seksi', $q);
    	//$this->db->or_like('SALDO_AWAL', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('IdSeksi', $q);
    	$this->db->or_like('IdBidang', $q);
    	$this->db->or_like('Seksi', $q);
    	//$this->db->or_like('SALDO_AWAL', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Seksi_model.php */
/* Location: ./application/models/Seksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-22 04:24:22 */
/* http://harviacode.com */